### PR TITLE
futurize first run

### PR DESCRIPTION
**Pull request by jooddang**
For the first step, I ran futurize against all python files. Any comments please?

### CODE REVIEW

**Comment by jooddang** [comment]
cc @mikhail

**Comment by mrterry** [comment]
make sure you the unittests pass on on both python2.7 and python 3.5

**Comment by jooddang** [comment]
@mrterry hmm. it's strange. It all passed before I created this pull request, but now it doesn't. gonna work on it.

**Comment by mikhail** [comment]
Closed via #67

**Pull request closed without merging**
